### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Tiago0** [Kreshnik/fbg-stats#1]
/ Fetching posts: 400C:\xxx\fbg-stats\dist\index.js:35188
                posts.push(new _Post2.default(post.from.id));
                                                       ^

TypeError: Cannot read property 'id' of undefined
    at C:\xxx\fbg-stats\dist\index.js:35188:56
    at Array.forEach (native)
    at Function.<anonymous> (C:\xxx\fbg-stats\dist\index.js:35187:29)
    at Graph.end (C:\xxx\fbg-stats\dist\index.js:44641:8)
    at Request._callback (C:\xxx\fbg-stats\dist\index.js:44669:10)
    at Request.self.callback (C:\xxx\fbg-stats\dist\index.js:62092:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\xxx\fbg-stats\dist\index.js:63075:10)
    at emitOne (events.js:96:13)

**Comment by Kreshnik** [comment]
Could you please provide me the group id for further debugging?

**Comment by Tiago0** [comment]
I'm sorry, i forgot to add.

420988311372905

**Comment by Kreshnik** [comment]
The issue, unfortunately, cannot be solved at the moment, the group seems to be private. Unless you are an admin, the script is not able to extract the post data.

**Comment by Tiago0** [comment]
Is a closed type group, anyone can see but needs approvement. Also i'm admin of it.

But thanks anyway.

**Comment by Kreshnik** [comment]
The following StackOverflow states the problem http://stackoverflow.com/a/40965682/1551070
